"""Strategist 2.0 domain contracts (Stage 15, Step 15A).

CONTRACTS ONLY — no strategist logic, no mapping from ContentCandidate,
no AI, no config, no persistence, no production wiring.

Strategist 2.0 must preserve the editorial decisions already made by the
SELECT stage. SELECT owns the cluster, format, target platforms and the
research/experiment flags; the Strategist MUST NOT randomly replace those
decisions later.

Field ownership in ``StrategistPlan``:

SELECT-preserved decisions (owned by SELECT, forwarded unchanged):

    candidate_id
    content_cluster
    content_format
    target_platforms
    research_required
    experiment_required

Strategist-owned enrichment (produced by Strategist 2.0 in a later step):

    topic
    angle
    hook
    objective
    cta
    cta_link
    tone
    structure
    language
    mode

The strategist-owned vocabularies (objective, tone, language, mode, ...)
are intentionally plain ``str`` — they are not stable enough yet to
justify new enums. No field has a default: every value must be supplied
explicitly so no strategy decision can happen silently. No validation,
no normalization, and no serialization (to_dict / from_dict) is defined
in this step.
"""

from dataclasses import dataclass
from typing import Tuple

from src.domain.strategy import (
    ContentCandidate,
    ContentCluster,
    ContentFormat,
    TargetPlatform,
)

__all__ = [
    "StrategistInput",
    "StrategistPlan",
]


@dataclass(frozen=True)
class StrategistInput:
    """Boundary object accepted by Strategist 2.0.

    Holds exactly the authoritative selected aggregate. The
    ``ContentCandidate`` fields are deliberately NOT duplicated here —
    the candidate itself is the single source of truth for discovery,
    verification, scoring and the SELECT decisions.
    """

    content_candidate: ContentCandidate


@dataclass(frozen=True)
class StrategistPlan:
    """Strategist 2.0 output contract.

    The SELECT-preserved decision fields must be forwarded unchanged from
    the selected ``ContentCandidate``; the strategist-owned fields are
    enrichment generated by the Strategist. Immutable (frozen) so a plan
    can never be quietly mutated after the SELECT decisions are bound.
    """

    candidate_id: str
    topic: str

    content_cluster: ContentCluster
    content_format: ContentFormat
    target_platforms: Tuple[TargetPlatform, ...]

    research_required: bool
    experiment_required: bool

    angle: str
    hook: str
    objective: str

    cta: str
    cta_link: str

    tone: str
    structure: Tuple[str, ...]

    language: str
    mode: str
